
;; "Basic-One and Two Dimensional NMR Spectroscopy" (2004, Horst Friebolin)


(setq symbols-used
      '(b0 "flux density"
	   b1b2 "radiofrequency field with frequency v1 and v2"
	   beff "effective field at position of nucleus"
	   C2 "two fold axis of symmetry"
	   chi "magnetic suceptibility"
	   13C+1H+ "Observation of 13C resonance while 1H is decoupled"
	   _delta "chemical shift relative to a standard (e.g. TMS)"
	   E "energy"
	   deltaE "energy difference between two states"
	   _delta "uncertainty in th energy of a state"
	   EA "Arrhenius activation energy"
	   EX "Electronegativity of a substituent X"
	   _eta "fractional enhancement in NOE"
	   _phi "phase difference between two vectors"
	   Phi "bond angle or dihedral angle"
	   F1F2 "frequency axes in a 2D NMR spectrum"
	   G "field gradient"
	   deltaG++ "Free Gibbs enthalpy of activation"
	   _gamma "gyromagnetic ratio, _-gamma = gamma/2pi"
	   _h "planck constant, _-h = h/2pi"
	   deltaH++ "Enthalpy of activation"
	   I "Nuclear angular momentum quantum number (spin)"
	   boldI "Nuclear spin operator"
	   nJ "Coupling constant through n bonds"
	   K "equilibrium constant"
	   _k "rate constant"
	   _kC "rate constant at the coalescence temperature T_C"
	   _kB "Boltzmann constant"
	   k_0 "frequency factor"
	   bold_mu "magnetic moment (of nucleus)"
	   _muz "component of magnetic moment along the static field direction (z axis)"
	   _m "magnetic quantum number"
	   bold_M0 "macroscopic magnetization of the sample in the static field B_0"
	   M_x.M_y. "transverse magnetization components in the x' and y' directions"
	   M_z "longitudinal magnetization in the z-direction (static field direction)"
	   M_X "magnetization vector for the X nuclei"
	   M_H_C_alpha "1H magnetization vectors in a two-spin system with the 13C nuclei in the alpha and beta states"
	   M_C_H_alpha "13C magnetization vectors in a two-spin system with the protions in the alpha and beta states"
	   N "total number of nuclei in the sample"
	   N_alphaN_beta "Numbers of nuclei in the alpha and beta states"
	   N_i "Number of nuclei in level i"
	   _nu "frequency"
	   _nuL "Larmor frequency"
	   _nui "Resonance frequency of nucleus i"
	   _nui "frequency of r.f. generator (observing frequency)"
	   _nu2 "decoupling frequency"
	   _nu1/2 "half height width"
	   bold_P "angular momentum of nucleus"
	   P_z "component of angular moment of nulceus in the z-direction"
	   Q "electric quadrupole moment"
	   R "Universal gas constant"
	   r "Interatomic or internuclear distance"
	   _sigma "shielding constant"
	   (S t) "signal as a function of time"
	   (S f) "signal as a function of frequency"
	   S_i "substittutent increment for predicting chemical shifts"
	   Delta_S++ "Entropy of activation"
	   _tau "time interval between pulses"
	   _tau_C "correlation time"
	   ))

